//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int IDDonHang { get; set; }
        public int IDHD { get; set; }
        public string TenSanPham { get; set; }
        public string DonViTinh { get; set; }
        public decimal GiaDonVi { get; set; }
        public decimal SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
